- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120Hrs
    TRAINER: sivakumar
  tasks:
  - name: print the variables
    anslible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }}, Trainer is {{ TRAINER }}"