- name: variables from command line args
  hosts: local
  connection: local
  tasks:
  - name: print the variables through cmmdline
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, Trainer is {{ TRAINER }}"