- name: check value is grater than 10 or not
  hosts: local
  connection: local
  vars:
    my_num: 15
  tasks:
  - name: print if num grater than 10
    ansible.builtin.debug:
      msg: "the no is{{ my_num }} is grater than 10"
    when: my_num > 10

  - name: print if num less than or equal to 10
    ansible.builtin.debug:
      msg: "the no is{{ my_num }} is less than or equal to 10"
    when: my_num <= 10  